
fiili_kullanim_amaclari = {
    1: "Arsa",
    2: "Arazi",
    3: "Konut",
    4: "Akaryakıt Tesisi",
    5: "Alışveriş Merkezi",
    6: "Dükkan-Mağaza",
    7: "Eğitim Tesisi",
    8: "Enerji Tesisi",
    9: "Ofis",
    10: "Sağlık Tesisi",
    11: "Turistik Tesis",
    12: "Sanayi ve Depolama Tesisi",
    13: "Spor-Sosyal Tesis",
    14: "Tarım-Hayvancılık Tesisi",
    15: "Diğer Ki/KM Kurulmamış Binalar"
}

zorunluluk_dict = {
  "Arsa": [
    "Fiili Kullanım Amacı",
    "Rapor No",
    "Değerleme Raporunun Faaliyet Kategorisi",
    "Uzman (TCKN)",
    "Uzman İstihdam Biçimi",
    "Sorumlu Değerleme Uzmanı (TCKN)",
    "SDU Adı",
    "SDU Soyadı",
    "Taşınmaz ID",
    "İl",
    "İlçe",
    "Mahalle/Köy (Takbis)",
    "Mevcut Mahalle/Köy",
    "Ada",
    "Parsel",
    "Parsel Yüzölçümü (m²)",
    "Ana Taşınmaz Niteliği",
    "Tapu Türü",
    "Tapu Tarihi",
    "Hisseli mi?",
    "Enlem",
    "Boylam",
    "Halihazır Kullanım Durumu",
    "Deprem Derecesi",
    "Kentsel Dönüşüm Bölgesinde mi?",
    "İmar Plan Ölçeği",
    "İmar Lejandı",
    "Yapı Nizamı",
    "Terk Sonrası Parselin Yüz Ölçümü (m²)",
    "Yasal Brüt Kullanım Alanı (m²)",
    "Mevcut Brüt Kullanım Alanı (m²)",
    "Yasal Kullanıma Esas Piyasa Değeri (TL)",
    "Mevcut Kullanıma Esas Piyasa Değeri (TL)",
  ],
  "Arazi": [
    "Rapor No",
    "Değerleme Kapsamı",
    "Değerleme Raporunun Faaliyet Kategorisi",
    "Fiili Kullanım Amacı",
    "Talep Tarihi",
    "Rapor Tarihi",
    "Bildirim Tarihi",
    "Bildiren Kişi",
    "Değerleme Kuruluşu Ünvanı",
    "Değerleme Kuruluşu Kodu",
    "Revize Talebi mi?",
    "Revize Tarihi",
    "Uzman (TCKN)",
    "Uzman Adı",
    "Uzman Soyadı",
    "Uzman İstihdam Biçimi",
    "Denetmen (TCKN)",
    "Denetmen Adı",
    "Denetmen Soyadı",
    "Sorumlu Değerleme Uzmanı (TCKN)",
    "SDU Adı",
    "SDU Soyadı",
    "Taşınmaz ID",
    "İl",
    "İlçe",
    "Mahalle/Köy (Takbis)",
    "Mevcut Mahalle/Köy",
    "Ada",
    "Parsel",
    "Parsel Yüzölçümü (m²)",
    "Ana Taşınmaz Niteliği",
    "Tapu Türü",
    "Tapu Tarihi",
    "Hisseli mi?",
    "Enlem",
    "Boylam",
    "Halihazır Kullanım Durumu",
    "Deprem Derecesi",
    "Kentsel Dönüşüm Bölgesinde mi?",
    "İmar Plan Ölçeği",
    "İmar Lejandı",
    "Yapı Nizamı",
    "Tarım Türü",
    "Arazi Sınıflandırması",
    "Kadastro Yoluna Cephesi Var Mı?",
    "Terk Sonrası Parselin Yüz Ölçümü (m²)",
    "Yasal Brüt Kullanım Alanı (m²)",
    "Mevcut Brüt Kullanım Alanı (m²)",
    "Yasal Kullanıma Esas Piyasa Değeri (TL)",
    "Mevcut Kullanıma Esas Piyasa Değeri (TL)",
  ],
  "Konut": [
    "Fiili Kullanım Amacı",
    "Rapor No",
    "Değerleme Kapsamı",
    "Değerleme Raporunun Faaliyet Kategorisi",
    "Talep Tarihi",
    "Rapor Tarihi",
    "Uzman (TCKN)",
    "Uzman İstihdam Biçimi",
    "Sorumlu Değerleme Uzmanı (TCKN)",
    "İl",
    "İlçe",
    "Mahalle/Köy (Takbis)",
    "Mevcut Mahalle/Köy",
    "Ada",
    "Parsel",
    "Parsel Yüzölçümü (m²)",
    "Ana Taşınmaz Niteliği",
    "Tapu Türü",
    "Tapu Tarihi",
    "Hisseli mi?",
    "İlk Kez mi Satışa Konu Ediliyor?",
    "Blok",
    "Kat",
    "Arsa Payı",
    "Arsa Paydası",
    "Site İçerisinde mi?",
    "Enlem",
    "Boylam",
    "Halihazır Kullanım Durumu",
    "Deprem Derecesi",
    "Kentsel Dönüşüm Bölgesinde mi?",
    "İmar Plan Ölçeği",
    "İmar Lejandı",
    "Yapı Nizamı",
    "Yapı Kullanma İzin Belgesi Var mı?",
    "Yapım Yılı",
    "Yapı Sınıfı ve Grubu",
    "Yapı Cinsi",
    "Yapı Kat Sayısı",
    "Enerji Sınıfı",
    "İnşaat Seviyesi",
    "Depreme Dayanıklılık ve Hasar Durumu",
    "Açık Otopark Var mı?",
    "Kapalı Otopark Var mı?",
    "Güvenlik Var mı?",
    "Asansör Var mı?",
    "Isınma Sistemi",
    "Yüzme Havuzu Var mı?",
    "Konut Türü",
    "Oda",
    "Salon",
    "Banyo",
    "Mutfak",
    "Balkon",
    "Cephe",
    "Yasal Brüt Kullanım Alanı (m²)",
    "Mevcut Brüt Kullanım Alanı (m²)",
    "Yasal Kullanıma Esas Piyasa Değeri (TL)",
    "Mevcut Kullanıma Esas Piyasa Değeri (TL)",
    "Arsa Birim Değeri (TL/m²)"
  ],
  "Akaryakıt Tesisi": [
    "Fiili Kullanım Amacı",
    "Rapor No",
    "Değerleme Raporunun Faaliyet Kategorisi",
    "Talep Tarihi",
    "Rapor Tarihi",
    "Uzman (TCKN)",
    "Uzman İstihdam Biçimi",
    "Sorumlu Değerleme Uzmanı (TCKN)",
    "İl",
    "İlçe",
    "Mahalle/Köy (Takbis)",
    "Mevcut Mahalle/Köy",
    "Ada",
    "Parsel",
    "Parsel Yüzölçümü (m²)",
    "Ana Taşınmaz Niteliği",
    "Tapu Türü",
    "Tapu Tarihi",
    "Hisseli mi?",
    "Kat",
    "Arsa Payı",
    "Arsa Paydası",
    "Enlem",
    "Boylam",
    "Halihazır Kullanım Durumu",
    "Deprem Derecesi",
    "Kentsel Dönüşüm Bölgesinde mi?",
    "İmar Plan Ölçeği",
    "İmar Lejandı",
    "Yapı Nizamı",
    "Yapı Kullanma İzin Belgesi Var mı?",
    "Yapım Yılı",
    "Yapı Sınıfı ve Grubu",
    "Yapı Cinsi",
    "Yapı Kat Sayısı",
    "Enerji Sınıfı",
    "İnşaat Seviyesi",
    "Depreme Dayanıklılık ve Hasar Durumu",
    "EPDK Lisansı Var mı?",
    "LPG Lisansı Var mı?",
    "Pompa Sayısı",
    "Pompa Satış Tutarı (Yıllık)",
    "Elektrikli Araç Şarj Ünitesi Var mı?",
    "En Yakın İstasyona Mesafe (km)",
    "Konum",
    "Üst Hakkı Var mı?",
    "Kalan Üst Hakkı Süresi (Ay)",
    "Yasal Brüt Kullanım Alanı (m²)",
    "Mevcut Brüt Kullanım Alanı (m²)",
    "Yasal Kullanıma Esas Piyasa Değeri (TL)",
    "Mevcut Kullanıma Esas Piyasa Değeri (TL)",
    "Aylık Kira Birim Değeri (TL/m²)",
    "Arsa Birim Değeri (TL/m²)"
  ],
  "Alışveriş Merkezi": [
    "Fiili Kullanım Amacı",
    "Rapor No",
    "Değerleme Raporunun Faaliyet Kategorisi",
    "Talep Tarihi",
    "Rapor Tarihi",
    "Bildirim Tarihi",
    "Uzman (TCKN)",
    "Uzman İstihdam Biçimi",
    "Sorumlu Değerleme Uzmanı (TCKN)",
    "İl",
    "İlçe",
    "Mahalle/Köy (Takbis)",
    "Mevcut Mahalle/Köy",
    "Ada",
    "Parsel",
    "Parsel Yüzölçümü (m²)",
    "Ana Taşınmaz Niteliği",
    "Tapu Türü",
    "Tapu Tarihi",
    "Hisseli mi?",
    "Bağımsız Bölüm Numarası",
    "Bağımsız Bölüm Niteliği",
    "Arsa Payı",
    "Arsa Paydası",
    "Enlem",
    "Boylam",
    "Halihazır Kullanım Durumu",
    "Deprem Derecesi",
    "Kentsel Dönüşüm Bölgesinde mi?",
    "İmar Plan Ölçeği",
    "İmar Lejandı",
    "Yapı Nizamı",
    "Yapı Kullanma İzin Belgesi Var mı?",
    "Yapım Yılı",
    "Yapı Sınıfı ve Grubu",
    "Yapı Cinsi",
    "Yapı Kat Sayısı",
    "Enerji Sınıfı",
    "İnşaat Seviyesi",
    "Depreme Dayanıklılık ve Hasar Durumu",
    "Açık Otopark Var mı?",
    "Kapalı Otopark Var mı?",
    "Asansör Var mı?",
    "Isınma Sistemi",
    "Mağaza Sayısı",
    "Kiralanabilir Alan (m²)",
    "Mağaza Doluluk Oranı (%)",
    "Aylık Ortalama Kira Birim Değeri (TL/m²)",
    "Yıllık Ziyaretçi Sayısı",
    "Zincir İşletme mi?",
    "Konumu",
    "Üst Hakkı Var mı?",
    "Kalan Üst Hakkı Süresi (Ay)",
    "Yasal Brüt Kullanım Alanı (m²)",
    "Mevcut Brüt Kullanım Alanı (m²)",
    "Yasal Kullanıma Esas Piyasa Değeri (TL)",
    "Mevcut Kullanıma Esas Piyasa Değeri (TL)",
    "Arsa Birim Değeri (TL/m²)"
  ],
  "Eğitim Tesisi": [
    "Fiili Kullanım Amacı",
    "Rapor No",
    "Değerleme Raporunun Faaliyet Kategorisi",
    "Talep Tarihi",
    "Rapor Tarihi",
    "Uzman (TCKN)",
    "Uzman İstihdam Biçimi",
    "Sorumlu Değerleme Uzmanı (TCKN)",
    "İl",
    "İlçe",
    "Mahalle/Köy (Takbis)",
    "Mevcut Mahalle/Köy",
    "Ada",
    "Parsel",
    "Parsel Yüzölçümü (m²)",
    "Ana Taşınmaz Niteliği",
    "Tapu Türü",
    "Tapu Tarihi",
    "Hisseli mi?",
    "Arsa Payı",
    "Arsa Paydası",
    "Enlem",
    "Boylam",
    "Halihazır Kullanım Durumu",
    "Deprem Derecesi",
    "Kentsel Dönüşüm Bölgesinde mi?",
    "İmar Plan Ölçeği",
    "İmar Lejandı",
    "Yapı Nizamı",
    "Yapı Kullanma İzin Belgesi Var mı?",
    "Yapım Yılı",
    "Yapı Sınıfı ve Grubu",
    "Yapı Cinsi",
    "Yapı Kat Sayısı",
    "Enerji Sınıfı",
    "İnşaat Seviyesi",
    "Depreme Dayanıklılık ve Hasar Durumu",
    "Güvenlik Var mı?",
    "Asansör Var mı?",
    "Isınma Sistemi",
    "Yüzme Havuzu Var mı?",
    "Zincir İşletme mi?",
    "Yasal Brüt Kullanım Alanı (m²)",
    "Mevcut Brüt Kullanım Alanı (m²)",
    "Yasal Kullanıma Esas Piyasa Değeri (TL)",
    "Mevcut Kullanıma Esas Piyasa Değeri (TL)",
    "Aylık Kira Birim Değeri (TL/m²)",
    "Arsa Birim Değeri (TL/m²)"
  ],
  "Enerji Tesisi": [
    "Fiili Kullanım Amacı",
    "Rapor No",
    "Değerleme Raporunun Faaliyet Kategorisi",
    "Talep Tarihi",
    "Rapor Tarihi",
    "Uzman (TCKN)",
    "Uzman İstihdam Biçimi",
    "Sorumlu Değerleme Uzmanı (TCKN)",
    "İl",
    "İlçe",
    "Mahalle/Köy (Takbis)",
    "Mevcut Mahalle/Köy",
    "Ada",
    "Parsel",
    "Parsel Yüzölçümü (m²)",
    "Ana Taşınmaz Niteliği",
    "Tapu Türü",
    "Tapu Tarihi",
    "Hisseli mi?",
    "Arsa Payı",
    "Arsa Paydası",
    "Enlem",
    "Boylam",
    "Halihazır Kullanım Durumu",
    "Deprem Derecesi",
    "Kentsel Dönüşüm Bölgesinde mi?",
    "İmar Plan Ölçeği",
    "İmar Lejandı",
    "Yapı Nizamı",
    "Yapı Kullanma İzin Belgesi Var mı?",
    "Yapım Yılı",
    "Yapı Sınıfı ve Grubu",
    "Yapı Cinsi",
    "Yapı Kat Sayısı",
    "Enerji Sınıfı",
    "İnşaat Seviyesi",
    "Depreme Dayanıklılık ve Hasar Durumu",
    "Güvenlik Var mı?",
    "Üst Hakkı Var mı?",
    "Kalan Üst Hakkı Süresi (Ay)",
    "Yasal Brüt Kullanım Alanı (m²)",
    "Mevcut Brüt Kullanım Alanı (m²)",
    "Yasal Kullanıma Esas Piyasa Değeri (TL)",
    "Mevcut Kullanıma Esas Piyasa Değeri (TL)",
    "Aylık Kira Birim Değeri (TL/m²)",
    "Arsa Birim Değeri (TL/m²)"
  ],
  "Ofis": [
    "Fiili Kullanım Amacı",
    "Rapor No",
    "Değerleme Raporunun Faaliyet Kategorisi",
    "Talep Tarihi",
    "Rapor Tarihi",
    "Uzman (TCKN)",
    "Uzman İstihdam Biçimi",
    "Sorumlu Değerleme Uzmanı (TCKN)",
    "İl",
    "İlçe",
    "Mahalle/Köy (Takbis)",
    "Mevcut Mahalle/Köy",
    "Ada",
    "Parsel",
    "Parsel Yüzölçümü (m²)",
    "Ana Taşınmaz Niteliği",
    "Tapu Türü",
    "Tapu Tarihi",
    "Hisseli mi?",
    "İlk Kez mi Satışa Konu Ediliyor?",
    "Arsa Payı",
    "Arsa Paydası",
    "Site İçerisinde mi?",
    "Sokak",
    "Enlem",
    "Boylam",
    "Halihazır Kullanım Durumu",
    "Deprem Derecesi",
    "Kentsel Dönüşüm Bölgesinde mi?",
    "İmar Plan Ölçeği",
    "İmar Lejandı",
    "Yapı Nizamı",
    "Yapı Kullanma İzin Belgesi Var mı?",
    "Yapım Yılı",
    "Yapı Sınıfı ve Grubu",
    "Yapı Cinsi",
    "Yapı Kat Sayısı",
    "Toplam Bağımsız Bölüm Sayısı",
    "Enerji Sınıfı",
    "İnşaat Seviyesi",
    "Depreme Dayanıklılık ve Hasar Durumu",
    "Açık Otopark Var mı?",
    "Kapalı Otopark Var mı?",
    "Güvenlik Var mı?",
    "Asansör Var mı?",
    "Isınma Sistemi",
    "Yüzme Havuzu Var mı?",
    "Ofis Türü",
    "Oda",
    "Salon",
    "Banyo",
    "Mutfak",
    "Balkon",
    "Cephe",
    "Yasal Brüt Kullanım Alanı (m²)",
    "Mevcut Brüt Kullanım Alanı (m²)",
    "Yasal Kullanıma Esas Piyasa Değeri (TL)",
    "Mevcut Kullanıma Esas Piyasa Değeri (TL)",
    "Aylık Kira Birim Değeri (TL/m²)",
    "Arsa Birim Değeri (TL/m²)"
  ],
  "Sağlık Tesisi": [
    "Fiili Kullanım Amacı",
    "Rapor No",
    "Değerleme Raporunun Faaliyet Kategorisi",
    "Talep Tarihi",
    "Rapor Tarihi",
    "Uzman (TCKN)",
    "Uzman İstihdam Biçimi",
    "Sorumlu Değerleme Uzmanı (TCKN)",
    "İl",
    "İlçe",
    "Mahalle/Köy (Takbis)",
    "Mevcut Mahalle/Köy",
    "Ada",
    "Parsel",
    "Parsel Yüzölçümü (m²)",
    "Ana Taşınmaz Niteliği",
    "Tapu Türü",
    "Tapu Tarihi",
    "Hisseli mi?",
    "Arsa Payı",
    "Arsa Paydası",
    "Enlem",
    "Boylam",
    "Halihazır Kullanım Durumu",
    "Deprem Derecesi",
    "Kentsel Dönüşüm Bölgesinde mi?",
    "İmar Plan Ölçeği",
    "İmar Lejandı",
    "Yapı Nizamı",
    "Yapı Kullanma İzin Belgesi Var mı?",
    "Yapım Yılı",
    "Yapı Sınıfı ve Grubu",
    "Yapı Cinsi",
    "Yapı Kat Sayısı",
    "Enerji Sınıfı",
    "İnşaat Seviyesi",
    "Depreme Dayanıklılık ve Hasar Durumu",
    "Açık Otopark Var mı?",
    "Kapalı Otopark Var mı?",
    "Güvenlik Var mı?",
    "Asansör Var mı?",
    "Isınma Sistemi",
    "Zincir İşletme mi?",
    "Yasal Brüt Kullanım Alanı (m²)",
    "Mevcut Brüt Kullanım Alanı (m²)",
    "Yasal Kullanıma Esas Piyasa Değeri (TL)",
    "Mevcut Kullanıma Esas Piyasa Değeri (TL)",
    "Aylık Kira Birim Değeri (TL/m²)",
    "Arsa Birim Değeri (TL/m²)"
  ],
  "Turistik Tesis": [
    "Fiili Kullanım Amacı",
    "Rapor No",
    "Değerleme Raporunun Faaliyet Kategorisi",
    "Talep Tarihi",
    "Rapor Tarihi",
    "Uzman (TCKN)",
    "Uzman İstihdam Biçimi",
    "Sorumlu Değerleme Uzmanı (TCKN)",
    "İl",
    "İlçe",
    "Mahalle/Köy (Takbis)",
    "Mevcut Mahalle/Köy",
    "Ada",
    "Parsel",
    "Parsel Yüzölçümü (m²)",
    "Ana Taşınmaz Niteliği",
    "Tapu Türü",
    "Tapu Tarihi",
    "Hisseli mi?",
    "Arsa Payı",
    "Arsa Paydası",
    "Enlem",
    "Boylam",
    "Halihazır Kullanım Durumu",
    "Deprem Derecesi",
    "Kentsel Dönüşüm Bölgesinde mi?",
    "İmar Plan Ölçeği",
    "İmar Lejandı",
    "Yapı Nizamı",
    "Yapı Kullanma İzin Belgesi Var mı?",
    "Yapım Yılı",
    "Yapı Sınıfı ve Grubu",
    "Yapı Cinsi",
    "Yapı Kat Sayısı",
    "Enerji Sınıfı",
    "İnşaat Seviyesi",
    "Depreme Dayanıklılık ve Hasar Durumu",
    "Açık Otopark Var mı?",
    "Kapalı Otopark Var mı?",
    "Güvenlik Var mı?",
    "Asansör Var mı?",
    "Isınma Sistemi",
    "Yüzme Havuzu Var mı?",
    "Turistik Tesisin Niteliği",
    "Yıldız Sayısı",
    "Oda Sayısı",
    "Tesis Doluluk Oranı (%)",
    "Yıl İçinde Açık Olduğu Gün Sayısı",
    "Yıllık Ortalama Oda Başına Fiyat (TL)",
    "Kıyı Kullanımı Var mı?",
    "Zincir İşletme mi?",
    "Konumu",
    "Üst Hakkı Var mı?",
    "Kalan Üst Hakkı Süresi (Ay)",
    "Yasal Brüt Kullanım Alanı (m²)",
    "Mevcut Brüt Kullanım Alanı (m²)",
    "Yasal Kullanıma Esas Piyasa Değeri (TL)",
    "Mevcut Kullanıma Esas Piyasa Değeri (TL)",
    "Aylık Kira Birim Değeri (TL/m²)",
    "Arsa Birim Değeri (TL/m²)"
  ],
  "Sanayi ve Depolama Tesisi": [
    "Fiili Kullanım Amacı",
    "Rapor No",
    "Değerleme Raporunun Faaliyet Kategorisi",
    "Talep Tarihi",
    "Rapor Tarihi",
    "Uzman (TCKN)",
    "Uzman İstihdam Biçimi",
    "Sorumlu Değerleme Uzmanı (TCKN)",
    "İl",
    "İlçe",
    "Mahalle/Köy (Takbis)",
    "Mevcut Mahalle/Köy",
    "Ada",
    "Parsel",
    "Parsel Yüzölçümü (m²)",
    "Ana Taşınmaz Niteliği",
    "Tapu Türü",
    "Tapu Tarihi",
    "Hisseli mi?",
    "Arsa Payı",
    "Arsa Paydası",
    "Enlem",
    "Boylam",
    "Halihazır Kullanım Durumu",
    "Deprem Derecesi",
    "Kentsel Dönüşüm Bölgesinde mi?",
    "İmar Plan Ölçeği",
    "İmar Lejandı",
    "Yapı Nizamı",
    "Yapı Kullanma İzin Belgesi Var mı?",
    "Yapım Yılı",
    "Yapı Sınıfı ve Grubu",
    "Yapı Cinsi",
    "Yapı Kat Sayısı",
    "Enerji Sınıfı",
    "İnşaat Seviyesi",
    "Depreme Dayanıklılık ve Hasar Durumu",
    "Güvenlik Var mı?",
    "Asansör Var mı?",
    "Isınma Sistemi",
    "Sanayi Depolama Tesisinin Niteliği",
    "OSB veya Serbest Bölge İçinde mi?",
    "Üst Hakkı Var mı?",
    "Kalan Üst Hakkı Süresi (Ay)",
    "Yasal Brüt Kullanım Alanı (m²)",
    "Mevcut Brüt Kullanım Alanı (m²)",
    "Yasal Kullanıma Esas Piyasa Değeri (TL)",
    "Mevcut Kullanıma Esas Piyasa Değeri (TL)",
    "Aylık Kira Birim Değeri (TL/m²)",
    "Arsa Birim Değeri (TL/m²)"
  ],
  "Spor-Sosyal Tesis": [
    "Fiili Kullanım Amacı",
    "Rapor No",
    "Değerleme Raporunun Faaliyet Kategorisi",
    "Talep Tarihi",
    "Rapor Tarihi",
    "Uzman (TCKN)",
    "Uzman İstihdam Biçimi",
    "Sorumlu Değerleme Uzmanı (TCKN)",
    "İl",
    "İlçe",
    "Mahalle/Köy (Takbis)",
    "Mevcut Mahalle/Köy",
    "Ada",
    "Parsel",
    "Parsel Yüzölçümü (m²)",
    "Ana Taşınmaz Niteliği",
    "Tapu Türü",
    "Tapu Tarihi",
    "Hisseli mi?",
    "Arsa Payı",
    "Arsa Paydası",
    "Sokak",
    "Enlem",
    "Boylam",
    "Halihazır Kullanım Durumu",
    "Deprem Derecesi",
    "Kentsel Dönüşüm Bölgesinde mi?",
    "İmar Plan Ölçeği",
    "İmar Lejandı",
    "Yapı Nizamı",
    "Yapı Kullanma İzin Belgesi Var mı?",
    "Yapım Yılı",
    "Yapı Sınıfı ve Grubu",
    "Yapı Cinsi",
    "Yapı Kat Sayısı",
    "Enerji Sınıfı",
    "İnşaat Seviyesi",
    "Depreme Dayanıklılık ve Hasar Durumu",
    "Açık Otopark Var mı?",
    "Kapalı Otopark Var mı?",
    "Güvenlik Var mı?",
    "Asansör Var mı?",
    "Isınma Sistemi",
    "Yüzme Havuzu Var mı?",
    "Yasal Brüt Kullanım Alanı (m²)",
    "Mevcut Brüt Kullanım Alanı (m²)",
    "Yasal Kullanıma Esas Piyasa Değeri (TL)",
    "Mevcut Kullanıma Esas Piyasa Değeri (TL)",
    "Aylık Kira Birim Değeri (TL/m²)",
    "Arsa Birim Değeri (TL/m²)"
  ],
  "Tarım-Hayvancılık Tesisi": [
    "Fiili Kullanım Amacı",
    "Rapor No",
    "Değerleme Raporunun Faaliyet Kategorisi",
    "Talep Tarihi",
    "Rapor Tarihi",
    "Uzman (TCKN)",
    "Uzman İstihdam Biçimi",
    "Sorumlu Değerleme Uzmanı (TCKN)",
    "İl",
    "İlçe",
    "Mahalle/Köy (Takbis)",
    "Mevcut Mahalle/Köy",
    "Ada",
    "Parsel",
    "Parsel Yüzölçümü (m²)",
    "Ana Taşınmaz Niteliği",
    "Tapu Türü",
    "Tapu Tarihi",
    "Hisseli mi?",
    "Arsa Payı",
    "Arsa Paydası",
    "Sokak",
    "Enlem",
    "Boylam",
    "Halihazır Kullanım Durumu",
    "Deprem Derecesi",
    "Kentsel Dönüşüm Bölgesinde mi?",
    "İmar Plan Ölçeği",
    "İmar Lejandı",
    "Yapı Nizamı",
    "Yapı Kullanma İzin Belgesi Var mı?",
    "Yapım Yılı",
    "Yapı Sınıfı ve Grubu",
    "Yapı Cinsi",
    "Yapı Kat Sayısı",
    "Enerji Sınıfı",
    "İnşaat Seviyesi",
    "Depreme Dayanıklılık ve Hasar Durumu",
    "Güvenlik Var mı?",
    "Üst Hakkı Var mı?",
    "Kalan Üst Hakkı Süresi (Ay)",
    "Yasal Brüt Kullanım Alanı (m²)",
    "Mevcut Brüt Kullanım Alanı (m²)",
    "Yasal Kullanıma Esas Piyasa Değeri (TL)",
    "Mevcut Kullanıma Esas Piyasa Değeri (TL)",
    "Aylık Kira Birim Değeri (TL/m²)",
    "Arsa Birim Değeri (TL/m²)"
  ],
  "Diğer Ki/KM Kurulmamış Binalar": [
    "Fiili Kullanım Amacı",
    "Rapor No",
    "Değerleme Raporunun Faaliyet Kategorisi",
    "Talep Tarihi",
    "Rapor Tarihi",
    "Uzman (TCKN)",
    "Uzman İstihdam Biçimi",
    "Sorumlu Değerleme Uzmanı (TCKN)",
    "İl",
    "İlçe",
    "Mahalle/Köy (Takbis)",
    "Mevcut Mahalle/Köy",
    "Ada",
    "Parsel",
    "Parsel Yüzölçümü (m²)",
    "Ana Taşınmaz Niteliği",
    "Tapu Türü",
    "Tapu Tarihi",
    "Hisseli mi?",
    "Arsa Payı",
    "Arsa Paydası",
    "Sokak",
    "Enlem",
    "Boylam",
    "Halihazır Kullanım Durumu",
    "Deprem Derecesi",
    "Kentsel Dönüşüm Bölgesinde mi?",
    "İmar Plan Ölçeği",
    "İmar Lejandı",
    "Yapı Nizamı",
    "Yapı Kullanma İzin Belgesi Var mı?",
    "Yapım Yılı",
    "Yapı Sınıfı ve Grubu",
    "Yapı Cinsi",
    "Yapı Kat Sayısı",
    "Enerji Sınıfı",
    "İnşaat Seviyesi",
    "Depreme Dayanıklılık ve Hasar Durumu",
    "Açık Otopark Var mı?",
    "Kapalı Otopark Var mı?",
    "Güvenlik Var mı?",
    "Asansör Var mı?",
    "Isınma Sistemi",
    "Yüzme Havuzu Var mı?",
    "Yasal Brüt Kullanım Alanı (m²)",
    "Mevcut Brüt Kullanım Alanı (m²)",
    "Yasal Kullanıma Esas Piyasa Değeri (TL)",
    "Mevcut Kullanıma Esas Piyasa Değeri (TL)",
    "Aylık Kira Birim Değeri (TL/m²)",
    "Arsa Birim Değeri (TL/m²)"
  ]
   
}
tamsayi_alanlari = [                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
    "Uzman Yardımcısı (TCKN)",
    "Uzman (TCKN)",
    "Denetmen (TCKN)",
    "Sorumlu Değerleme Uzmanı (TCKN)",
    "Taşınmaz ID",
    "Ada",
    "Parsel",
    "Arsa Payı",
    "Arsa Paydası",
    "Yapı Kat Sayısı",
    "Toplam Bağımsız Bölüm Sayısı",
    "Oda",
    "Salon",
    "Banyo",
    "Mutfak",
    "Balkon",
    "Dağıtımcı ile Kalan Anlaşma Süresi (Ay)",
    "Pompa Sayısı",
    "En Yakın İstasyona Mesafe (km)",
    "Mağaza Sayısı",
    "Yıllık Ziyaretçi Sayısı",
    "Yıldız Sayısı",
    "Oda Sayısı",
    "Yıl İçinde Açık Olduğu Gün Sayısı",
    "Kalan Üst Hakkı Süresi (Ay)" 
]

ondalik_alanlari = [
    "Parsel Yüzölçümü (m²)",
    "Enlem",
    "Boylam",
    "TAKS",
    "KAKS",
    "Hmax",
    "Terk Sonrası Parselin Yüz Ölçümü (m²)",
    "Pompa Satış Tutarı (Yıllık)",
    "Yan Gelirler (Yıllık)",
    "Kiralanabilir Alan (m²)",
    "Aylık Ortalama Kira Birim Değeri (TL/m²)",
    "Yıllık Ortalama Oda Başına Fiyat (TL)",
    "Yasal Brüt Kullanım Alanı (m²)",
    "Mevcut Brüt Kullanım Alanı (m²)",
    "Yasal Kullanıma Esas Piyasa Değeri (TL)",
    "Mevcut Metrekare Birim Değeri (TL/m²)",
    "Yasal Kullanıma Esas Piyasa Değeri (USD)",
    "Mevcut Kullanıma Esas Piyasa Değeri (TL)",
    "Mevcut Kullanıma Esas Piyasa Değeri (USD)",
    "Aylık Kira Birim Değeri (TL/m²)",
    "Arsa Birim Değeri (TL/m²)"
]

karakter_alanlari = {
    "Mahalle/Köy (Takbis)": {
        "max_karakter": 50,
        "zorunlu": True
    },
    "Mevcut Mahalle/Köy": {
        "max_karakter": 50,
        "zorunlu": True
    },
    "Ana Taşınmaz Niteliği": {
        "max_karakter": 250,
        "zorunlu": True
    },
    "Blok": {
        "max_karakter": 20,
        "zorunlu": False
    },
    "Kat": {
        "max_karakter": 20,
        "zorunlu": False
    },
    "Bağımsız Bölüm Numarası": {
        "max_karakter": 20,
        "zorunlu": False
    },
    "Bağımsız Bölüm Niteliği": {
        "max_karakter": 250,
        "zorunlu": False
    },
    "Bulvar/Cadde": {
        "max_karakter": 50,
        "zorunlu": False
    },
    "Sokak": {
        "max_karakter": 50,
        "zorunlu": False
    },
    "Dağıtımcı Markası": {
        "max_karakter": 250,
        "zorunlu": False
    }

          } 
